project:
  type: website

website:
  title: "Finist'R 2025"
  navbar:
    left:
      - icon: github
        href: https://github.com/StateOfTheR/finistR2025
        aria-label: GitHub
      - text: "Instructions"
        href: instructions.qmd
    right:
      - text: Diff√©rentiation automatique
        menu:
          - text: Autodiff avec JAX et torch
          - href: autodiff.qmd
          - text: Tuto autodiff StateOfTheR
          - href: tuto_autodiff.qmd
      - text: animint2
        href: animint.qmd
      - icon: Bicycle
        href: traccar.qmd
        text: GPS -- traccar
format:
  html:
    theme: flatly
    highlight: tango
    toc: true
    
