project:
  type: website

website:
  title: "Finist'R 2025"
  navbar:
    left:
      - icon: github
        href: https://github.com/StateOfTheR/finistR2025
        aria-label: GitHub
      - text: "Instructions"
        href: instructions.qmd
    right:
      - text: DiffÃ©rentiation automatique
        href: autodiff.qmd
      - text: animint2
        href: inimint.qmd
      - icon: Bicycle
        href: traccar.qmd
        text: GPS -- traccar
>>>>>>> main
format:
  html:
    theme: flatly
    highlight: tango
    toc: true
    
