project:
  type: website

website:
  title: "Finist'R 2025"
  navbar:
    left:
      - icon: github
        href: https://github.com/StateOfTheR/finistR2025
        aria-label: GitHub
      - text: "Instructions"
        href: instructions.qmd
    right:
      - text: Développement
        menu:
          - text: How to build your package - Julia edition
            href: how_to_build_your_package.qmd
          - text: Positron
            href: positron.qmd
          - text: Python packaging
            href: package_python.qmd
      - text: Différentiation automatique
        menu:
          - text: Autodiff avec JAX et torch
          - href: autodiff.qmd
          - text: Tuto autodiff StateOfTheR
          - href: tuto_autodiff.qmd
      - text: animint2
        href: animint.qmd
      - text: HMSC
        href: hsmc.qmd  
      - icon: Bicycle
        href: traccar.qmd
        text: GPS -- traccar
      - text: Sparse Cholesky
        href: sparse_cholesky.qmd
      - href: GNNpytgeo.qmd
        icon: share-fill
        text: Échantillonnage pour GNN
format:
  html:
    theme: flatly
    highlight: tango
    css: styles.css
    toc: true
    
resources: package_python_tuto_annexe.qmd 
